### ISSUE TITLE
Virtual-Tour arrow vs. videoLayer

### ISSUE THREAD

**Issue by Mr-Kanister** [mistic100/Photo-Sphere-Viewer#1126]
### Describe the bug

If you click an arrow from the virtual tour plugin while it is over a videoLayer from the markers plugin, the click gets transferred to the videoLayer but not to the arrow.

See the JSFiddle: If you click the link to the second node, while it is directly over rick, rick gets played/paused. I would expect it to change node instead.

### Online demo URL

https://jsfiddle.net/0vtxcLf4/

### Photo Sphere Viewer version

5.4.4

### Plugins loaded

Markers, Virtual-Tour

### OS & browser

Windows, Firefox

**Comment by mistic100** [comment]
The problem is the markers plugin does a "stopImmediatePropagation" to prevent the viewer click event (unless "clickEventOnMarker" option is true). And there is no way to give prority to events listeners.

Two solutions :
- set clickEventOnMarker: true on the markers plugin
- register the markers plugin **after** to virtual tour plugin

**Comment by Mr-Kanister** [comment]
Oh wow, interesting to know that the order of the plugins does make a difference in this special case!
Thanks for the response 👍🏼
