### ISSUE TITLE
Virtual Tour: name of link doesn't get displayed

### ISSUE THREAD

**Issue by Mr-Kanister** [mistic100/Photo-Sphere-Viewer#1190]
### Describe the bug

Hi there,
the name attribute of a link should override the tooltip of the link. Unfortunately it is not doing that.

See the demo URL: The tooltip of the link to the third node should be "This doesn't get displayed" instead of "Three". The standard name doesn't get overwritten though.

Thanks for your brilliant work!

### Online demo URL

https://jsfiddle.net/30crw6ep/2/

### Photo Sphere Viewer version

5.5.1

### Plugins loaded

virtual-tour-plugin

### OS & browser

Debian 12, Firefox 115.5.0esr

**Comment by mistic100** [comment]
This is also the case for `gps`, the original intend was not to allow overring values but provide them synchronously before loading the linked node data.

I admit the documentation is misleading ?

I there a real use case for overriding the node name for a specific link ?

**Comment by Mr-Kanister** [comment]
For me there certainly is a use case: on a staircase, I would like the link to say "Up" when coming from downstairs, but "Down" when coming from upstairs. However, the node itself might be called "Staircase", for example.

**Comment by mistic100** [comment]
So because the tooltip can also contain the thumbnail and the caption if they are defined I removed `link.name` anyway.

But I added a new option to customize the tooltip at will.

---

#### `getLinkTooltip(content, link, node)`

-   type: `function(string, link, node) => string`
-   default: `null`
-   updatable: no

Callback used to replace/modify the tooltip for a link. The first parameter is the default tooltip content which contains the node `name` + `thumbnail` + `caption`.

---

Remember that the links have a `data` property where you can store any useful data

```js
getLinkTooltip(content, link) {
  return link.data.myTooltip;
}
```

**Comment by Mr-Kanister** [comment]
Thanks, I will look into it.

**Comment by Mr-Kanister** [comment]
Alright, I tried it and it does work. But the style of the tooltip is completely off. Am I using it wrong?

See this demo: https://jsfiddle.net/u9ox1bLq/2/

The tooltip on the link to the third node does get changed but it has no background, the arrow is in the middle of the text and the overflow is cursed.

**Comment by mistic100** [comment]
That's because of this https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/virtual-tour-plugin/src/style.scss#L14

I will try to fix that.

In the meantime wrap you custom tooltip in a `<p>` tag

**Comment by Mr-Kanister** [comment]
I see. Thank you very much for your quick response!
