### ISSUE TITLE
Equirectangular - interpolateBackground 

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1301]
### Describe your problem

I tried to use the `interpolateBackground` option to fill the missing parts of a pano

https://www.tadini.it/temp/panorama_PXL.html

I got an error that I cannot understand. 

Chrome 124 - Win 11

### Online demo URL

https://www.tadini.it/temp/panorama_PXL.html

### Photo Sphere Viewer version

5.7.3

**Comment by mistic100** [comment]
Your panorama is just too big, it works fien when resizing it to 8000px wide or so.

Also because the image contains black on the top and bottom, the interpolated content is just black.

You should know that none of your panorama works on Firefox which is unable to load such large textures. You should use the tiles system https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html (which does not perform interpolation)
