### ISSUE TITLE
VirtualTourPlugin not working properly with AutorotatePlugin and StereoPlugin

### ISSUE THREAD

**Issue by zatakiya** [mistic100/Photo-Sphere-Viewer#1449]
### Describe the bug

While using auto rotate plugin with virtual tour, autorotation stops after the node is changed.

Also, when StereoPlugin is activated and clicked anywhere on the screen (including link arrow button), one side of screen just disappears

Seems like StereoPlugin is currently not supported to work with VirtualTourPlugin, but it could be a very good addition. 

### Photo Sphere Viewer version

5.10.1

### Plugins loaded

VirtualTourPlugin, AutorotatePlugin, GyroscopePlugin, StereoPlugin

### OS & browser

Tested in windows(Chrome) and ios(Safari).

### Additional context

I am using this in nextjs project, with react-photo-sphere-viewer framework. Not sure if this issue is related to react-photo-sphere-viewer only or not.

**Comment by mistic100** [comment]
I made some changes to improve the integration of the autorotate feature inside virtual-tour : the rotation will still stops when changing node, because this is considered a user interraction, but it will re-start again if `autostartOnIdle: true` (the default).

I do not plan to make improvements on the stereo integration, I don't think there is a real usage of cardboards justifying to fix each edge case.

**Comment by zatakiya** [comment]
Thanks for the quick reply

I believe making stereo plugin compatible with virtual tour can enable the functionality to view virtual tour in VR headsets. Or am I missing something here?

**Comment by mistic100** [comment]
the stereo plugin is not an XR renderer, there is another issue for that #571 which I do not work on
