### ISSUE TITLE
poseHeading with 5.11

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1459]
### Describe your problem

Hello Damien,

I don't think it's related with the new viewer.`useNewAnglesOrder` ; maybe with the new panodata more flexible options...

I don't know.

but with 5.10.1 the poseheading was correct and therefore markers and north direction are shown in the correct position
https://www.tadini.it/temp/panorama_segname_5101.html

with 5.11 poseheading is shifted
https://www.tadini.it/temp/panorama_segname.html

In this 5.11 I also used   `viewer.useNewAnglesOrder = false;` just to see if that was the problem. It doesn't seem so.

Thank You as always for your patience.

### Photo Sphere Viewer version

5.11.0

**Comment by mistic100** [comment]
It is not `viewer.useNewAnglesOrder = false` it is `Viewer.useNewAnglesOrder = false` (with un uppercase V) because it is a static property.

And this is totally related to this change, you can check the code here.

https://github.com/mistic100/Photo-Sphere-Viewer/blob/7fc1a030896e2135a84d0da064e38498c236ffe0/packages/core/src/services/Renderer.ts#L297-L301

You will have to invert all your `poseHeading`

**Comment by haldo98** [comment]
No problem at all. Thank You for your great work.

**Comment by mistic100** [comment]
Just so you know : I noticed your demos never load in Firefox because your files are very large. I have now fixed this latent issue, it will be shipped with the next patch version.

https://github.com/mistic100/Photo-Sphere-Viewer/commit/292805348cc4d58f1cf398e520ef2436377d62b4

**Comment by haldo98** [comment]
oh.. Thank You. I never noticed that. I use chrome and edge mostly.
Thank You.
