### ISSUE TITLE
Incompatible with Latest Google chrome version 60.

### ISSUE THREAD

**Issue by kelishrestha** [mistic100/Photo-Sphere-Viewer#147]
## Issues guidelines

- The following error is shown in google chrome version 60.0.3112.90.
- It works fine in older version.

The error can be seen in  the official site itself.

**Screenshot**

<img width="1434" alt="screen shot 2017-08-18 at 5 47 13 pm" src="https://user-images.githubusercontent.com/10415266/29458263-ec75a548-843d-11e7-810b-c8d3bf5b0f1f.png">

**Comment by ramanamatya** [comment]
Same for me :(

**Comment by mistic100** [comment]
You shouldn't have to use the Canvas Renderer on Chrome, unless you have a computer with zero graphic chipset (thus no WebGL support) which is very not likely to be the case in 2017.

Do you use the lastest version of Three ? It seems that the API has changed since r70 (the version used on the demo website)

**Comment by ramanamatya** [comment]
@mistic100 Thank you, I removed the Canvas Renderer and it worked fine on the new version as well.

**Comment by whileHelio** [comment]
Sorry the silly question,but how did you removed Canvas Renderer?
