### ISSUE TITLE
Bug Cubemap Image Circulation Button Double Click

### ISSUE THREAD

**Issue by chuckfairy** [mistic100/Photo-Sphere-Viewer#224]
Linux Chrome Latest

On the cubemap example, try clicking the image circulation/rotation button **twice** quickly. You'll get a `Loading already in progress` error. When this error happens you will be unable to switch back even after loading is done. This is only on cubemap from my tests.

**Comment by mistic100** [comment]
It is not really a bug but how the example is coded : it will cycle between the two panoramas whichever the transition is successful or not, which lead to a broken cycle. The viewer itself is fine.

There is not problem in the equirectangular example because I added a loading state, will do in the cubemap example too.
