### ISSUE TITLE
black screen using firefox?

### ISSUE THREAD

**Issue by kadrim** [mistic100/Photo-Sphere-Viewer#363]
Hi there!

i really love to use photospheres but for me it seems not to work correctly.

On all Windows (10) devices with Firefox (currently v 75) the Panoramas won't display. On Chrome and Edge (also Chrome) everything is fine. Even on mobile phones (Android 10) with firefox the Panorama is displayed.

But on the Desktop Firefox everything is Black. This also happens on Firefox 75.0 64bit (Ubuntu 18.04).

I originally posted this issue for photo-sphere-viewer on nextcloud (https://github.com/nextcloud/files_photospheres/issues/41)

and wit the help of @R0Wi we discovered that this must be an upstream bug or related to the picture itself.

@R0Wi prepared some test cases which i currently host on my servers:

http://tyrael.metaname.de/example/panorama1.html (same library version as used in the NC-app)

http://tyrael.metaname.de/example/panorama2.html (latest stable release 3.6.0)

http://tyrael.metaname.de/example/panorama3.html (4.0.0 alpha)

Thanks in advance!

**Comment by mistic100** [comment]
Your image is way too big !
It will be resized to the MAX_TEXTURE_SIZE supported by the browser, which is 16384 on chrome and 8192 on Firefox.

```
const canvas = document.createElement('canvas');
const ctx = canvas.getContext('webgl');
ctx.getParameter(ctx.MAX_TEXTURE_SIZE);
```

You probably get a black image because the system is struggly to resize the picture.
Use 8192 pixels wide image and you will be fine.

The resize is done using standard canvas API, nothing can be done to improve this in the lib.
