### ISSUE TITLE
Can't get gyroscope plugin to work

### ISSUE THREAD

**Issue by dbleyenda** [mistic100/Photo-Sphere-Viewer#367]
Hello, I can't get gyroscope plugin to work. I made a JS Fiddle with what I'm using. Please any help is welcome.

When I open that fiddle in a mobile device the console.log that check if gyroscope plugin is enabled, they always return false, even if I try to start it manually.

https://jsfiddle.net/dbleyenda/2kLwv9bf/11/

**Comment by mistic100** [comment]
First of all `gyroscopePlugin.start()` returns a Promise, so obviously it is not enabled straith away.

Secondly there is clear warning in the console :
> The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features

I suspect it's because jsfiddle run into a iframe and it's `allow` parameter is missing `gyroscope` https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs

The demo works perflectly (tested just now).

**Comment by dbleyenda** [comment]
Thanks for your reply. After several weeks of trying, I understood that gyroscope won't work without https, that's why it wasn't working at all. 

Thanks again.
