### ISSUE TITLE
Fullscreen error on iPhone

### ISSUE THREAD

**Issue by zqdevelopment** [mistic100/Photo-Sphere-Viewer#446]
## Issues guidelines

I use the last (dist) version of Photo-Sphere-Viewer, three.js and web browser.
All elements work well. But when I open the plugin on my iPhone and click on the full screen button, nothing happens. I also tried to open the full screen on your site (https://photo-sphere-viewer.js.org/) but it didn't work either.
I use 6 plus iPhone on iOS version 12.4.8 and also tried it on iPhone 8 plus version 13.4.1

**Comment by jumpjosh** [comment]
Hello! Maybe this will help (or maybe not), but from what I understand iPhones (iOS Safari) are notoriously bad at handling full screen. They often just do nothing. So, a way of fixing this used by some players is to practically just resize the player to full viewport height/width when the Fullscreen button is clicked. Not true fullscreen because it keeps browser UI I think, but it's better than nothing.

Unfortunately I don't know javascript well enough to provide the code for this, but I have read many articles talking about it and ways around it so it should be possible.

**Comment by mistic100** [comment]
The fullscreen method already does a "hack" when the API is not available https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/Viewer.js#L845-L854

The problem I think is that iOS exposes the API but it does not work.

**Comment by vekin03** [comment]
Yes, I have the same problem.

I tried to add the following meta tags, but no luck:

```
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
```
