### ISSUE TITLE
Zoom controls disappear after opening "Device toolbar" in Chrome

### ISSUE THREAD

**Issue by JuxhinB** [mistic100/Photo-Sphere-Viewer#451]
PSV - v4.0.7

While you develop with the "Device Toolbar" activated. If you are to click one of the bottom tools what happens is that the zoom controls dissappear and than you can click the rest of the options normally.
But still you don't have access to the zoom controls.

**Comment by amaze-escape** [comment]
Same issue here. Zoom controls dissapear when clicking a custom button in the toolbar.

**Comment by mistic100** [comment]
FYI this is because the only reliable way to detect you are on a touch device is to listen to touch events. And I have choosen to hide zoom buttons on touch devices to gain space on the viewer navbar.

Indeed the Chrome debugger does not have multi-touch emulation to be able to zoom.
Right now I have no solution.
