### ISSUE TITLE
Mouse click position over polygon marker

### ISSUE THREAD

**Issue by shtrudelsupport** [mistic100/Photo-Sphere-Viewer#473]
Hi there,

How can I get the mouse click position (relative to container or marker) when clicked over polygon marker ?

Thanks in advance.

**Comment by mistic100** [comment]
Getting the position of the cursor in the marker makes no sense because the marker adapts to the POV.

In the click event you have :
- clientX/clientY :  absolute cursor position
- viewerX/viewerX : relative cursor position to the viewer container
- longitude/latitude : as it says
- textureX/textureY : cursor position in the panorama image

**Comment by mistic100** [comment]
This info should be available in the documentation but it is currently broken (#474)

**Comment by mistic100** [comment]
I forgot to say that for this to work you need to configure `clickEventOnMarker`  
https://photo-sphere-viewer.js.org/plugins/plugin-markers.html#configuration
