### ISSUE TITLE
How to make progress bar more accurate?

### ISSUE THREAD

**Issue by syzdev** [mistic100/Photo-Sphere-Viewer#544]
1. Every time I load a picture, the round progress bar will finish loading quickly, but the page needs to wait several seconds before it will be displayed. I want to know if I can make the progress bar more accurate (the page will be displayed at the end of loading).
2. Is there any way to speed up the loading of picture?
3. In my program, I need to switch picture. At present, my switching method is `setPanorama`. When I switch picture, the screen will stop until the new picture is loaded successfully. I want to know whether I can perform other operations when I switch picture, such as adding a zoom effect to the destination to improve the user experience.

**Comment by mistic100** [comment]
1. this is the responsibility of you server, browser and connection, if for any reason the browser can't determine the loading progress, neither can the library. Bu I can assure you all as been done to display the progress when it is known.

Also if you experience lag after the load but before the display, it is because the image needs to be transferred from the RAM to the GPU, and this can be expansive on small rigs. Again nothing that can be done.

2. Reduce the size of your image ? there is no magic.

3. See 1. if the browser is stuck transferring the texture, nothing can be animated.

----

These problems would be reduced with the new tiles support in the next major version, demo here https://photo-sphere-viewer.js.org/guide/adapters/tiles.html  
smaller textures => less overhead when transferring to the GPU

**Comment by mistic100** [comment]
Things you can do :

- Call `viewer.texyureLoader.preloadPanorama(url)` in advance.
- Call `setPanorama(url, { transition: false })` and wrap everything in a custom Animation
    example of using the Animation helper https://photo-sphere-viewer.js.org/demos/intro.html

**Comment by syzdev** [comment]
Thank you for your patient help.
I will try these solutions and watch for future updates to the project.
