### ISSUE TITLE
Marker position issue  - Mobile

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#638]
https://www.tadini.it/photosphere/test/panorama_bassetta.htm

if i watch this pano in my chrome browser and pc no issue.... the marker are positioned correctly

If I watch the same pano with chrome on my xiaomi MI 11 the marker are shifted several degrees to the right

same here:     https://www.tadini.it/photosphere/test/panorama_canciano.htm  the markers are shifted for some degrees to the right

but here no problem....   https://www.tadini.it/photosphere/test/panorama_bregagno.htm

Thank You.

**Comment by mistic100** [comment]
So investigated a bit and discovered that the image received on Chrome Android is **not** the same size than the original.

Your original image is 17701 pixels wide while the image loaded on Chrome Android is 15489 pixels wide, and this is independant of Photo Sphere Viewer, I tried with a simple `img` element.  
I don't know why this happens, perhaps some bandwidth optimization service provided by Google.

Anyway there is nothing I can do. Your only solution is to reduce the size of your image. Also note that whatever size you use, it will alsways be downsized to 4096 pixels by Photo Sphere Viewer (16348 on desktop), because this is the maximum texture size supported by WebGL (although this downsizing is correctly handled by the lib).


----

On a side note be aware that the next version (4.5.0) will break your x/y coordinates because I fixed a bug where the coordinate conversion was wrong when using `poseHeading` .

For exemple you placed the "Monte Legnone" marker at `19046/875` when its actual position is more `15614/875` (check with Photoshop).

**Comment by mistic100** [comment]
Of course if you use longitude/latitude positionning instead of x/y you won't have any problem.

**Comment by haldo98** [comment]
Thank You.

In order to batch resize all the panos...   the width must be 16384 pixels or lower.  Correct?

**Comment by mistic100** [comment]
I don't know, as said the loaded image on Chrome Android is 15489 pixels. Does it resize anything above 16384 to an arbitrary size ? or does it resize anything above 15489 ? I can only by trying and do a debug session on you device to check the actual image size.

**Comment by haldo98** [comment]
Thank You.. I will try some size and see what comes out...


I must say that since the downsize from PSV is to 16384 ... trying with, for instance, 15000 .. there will not be so much difference..


anyway i did not understand the 4096 reference you wrote....

**Comment by mistic100** [comment]
What to you don't understand ? The limit is 16384 on desktop and 4096 on mobile. That's it

You can check it here https://webglreport.com/?v=2 on the blue "Textures" card.

**Comment by haldo98** [comment]
ok..  4096 is the limit on mobile... 

this is what i did not know....  Now I do.

Thank you

**Comment by mistic100** [comment]
I just made a test https://www.strangeplanet.fr/test-image/  
this load a 16384 image and display the actual size.... it shows 10240 on my smartphone.

So I don't what are the rules, I cannot find any resource about this.

My only advice is to not use x/y coordinates as it is not reliable.

**Comment by haldo98** [comment]
Thank You....   !!!!   very kind of you.

As you suggested before....   I'm converting all the x/y into long/lat  with an excel worksheet that does the calculation. (almost done... only something to figure out)

Thanks.
