### ISSUE TITLE
"Jerk" when panning

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#723]
When panning in the viewer with the inertia setting enabled, the is an odd visual "jerk" on release of the click where inertia takes over. See below video of the [playground example](https://photo-sphere-viewer.js.org/playground.html). 

With inertia setting on:

https://user-images.githubusercontent.com/47948499/185476602-68499a3e-9f3e-4b8a-92c7-88fe5b5da65b.mp4

With inertia setting off:

https://user-images.githubusercontent.com/47948499/185476623-d33cb8b7-6896-43bf-8bfc-88639659bf0d.mp4

**Comment by mistic100** [comment]
If you have an implementation proposal feel free to contribute. Personnally I was never able to fix this.

For the reference, both "competing" librairies, Panolens and Pannellum, have similar problems.  
In PSV in only happens when doing a short & fast move and release the mouse button before ~500ms.

**Comment by mistic100** [comment]
Okay so... the code managing the inertia was 5 years old, and utterly flawed. I am even suprised it worked at all.

Now it is fixed

**Comment by mikepianka** [comment]
@mistic100 your change definitely helped. I made PR #726 which should help make it even smoother. I think the key is using an easing method with a more linear start to avoid an acceleration bump like you talked about being more evident for small mouse moves.
