### ISSUE TITLE
Moving Pano with keyboard arrows

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#740]
Is it possible to move the panorama around using the arrows on the keyboard?

I checked all the options but are related only with the mouse.

Thank You.

**Comment by mistic100** [comment]
I don't know how you search... the option is named `keyboard` https://photo-sphere-viewer.js.org/guide/config.html#keyboard

**But** it only works in fullscreen, because the otherwise the viewer does not know it has focus. I though it would too "secret" to enable keyboard only after the user has clicked at least once on the viewer.

Another solution, if you have full control of your application is to call `viewer.startKeyboardControl()`. But remember it will be global to the page.

**Comment by haldo98** [comment]
Great!!!!    

Thank You. Always kind.
