### ISSUE TITLE
Property does not exist on Viewer event type

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#835]
### Describe the bug

When following the examples for v5 Viewer events, TS is throwing type errors when trying to destructure data from the events. See image below with a simple example. The same behavior happens for other event/data combinations like `"dblclick", ({ data })`, `"position-updated", ({ position })`, and `"zoom-updated", ({ zoomLevel })`.

![image](https://user-images.githubusercontent.com/47948499/212968781-e8d1fb53-7515-4e1b-9f96-883edb0d4e7a.png)

When I try the same thing for the virtual tour plugin `node-changed` event, that works fine with no errors:

![image](https://user-images.githubusercontent.com/47948499/212970467-5024455d-a67b-46d9-aea8-d79bb679d039.png)

### Photo Sphere Viewer version

5.0.2

### OS & browser

Windows 10 / Chrome

**Comment by mistic100** [comment]
I think this is because multiple events in the Viewer namespace have a `data` property.

I don't know what is the solution here, I cannot rename the properties, and I don't exactly understand how it works anyway (the solution was taken from a blog, the link is in the comment).  
https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/core/src/lib/TypedEventTarget.ts

The type check can be by-passed with this, but it is dumb.

```ts
this.viewer.addEventListener<any, any>('click', ({ data }: events.ClickEvent) => {
});
```

Personally I never had the issue when implementing the plugins because I use the  EventListenerObject pattern everywhere, which by essence breaks the type-check.

**Comment by mistic100** [comment]
Nope, the same problem arises with the "fullscreen" event, and only this event has a `fullscreenEnabled` property.

**Comment by mistic100** [comment]
Okay this is as soon are there are multiple event types on a single emitter. Still don't know what is the solution.

**Comment by mistic100** [comment]
Change is broken, it compiles but does not run because it tries to write "type" which is readonly.
