### ISSUE TITLE
Navbar controls not visible

### ISSUE THREAD

**Issue by pcolmer** [mistic100/Photo-Sphere-Viewer#955]
### Describe the bug

With this configuration:

```
<script>
    const viewer = new PhotoSphereViewer.Viewer({
        container: document.querySelector('#viewer'),
        panorama: '/assets/img/PXL_20230504_043331770.PHOTOSPHERE.jpg',
        navbar: [
            "zoom", "move", "fullscreen"
        ],
        caption: "The Living Room and decks 2 and 3"
    });
</script>
```

the only control that appears is the fullscreen control. I have occasionally seen the other controls be added to the navbar but I cannot be sure or clear about what triggers their visibility.

### Online demo URL

https://techietravelling.papillonproductions.co.uk/2023/05/04/day6.html

### Photo Sphere Viewer version

5.1.5

### OS & browser

Windows 11 + Edge

**Comment by mistic100** [comment]
They are masked because the browser announce to be running on a touch support system. If you click once on the viewer the library will detect that it is actually not the case (**this setting is persisted in local storage**).  
This is not a bug, this is the only reliable way to detect touch screens.

Implementation is here https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/core/src/data/system.ts#L112-L149

If for some reason you want to disable this, you can set the LS variable before loading the viewer `localStorage['photoSphereViewer_touchSupport'] = false`, but all the buttons will always be visible, even on small touch screens
